# Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: freshness
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: web
    port: 3000
    targetPort: 3000
    nodePort: 30300  # Access Grafana at <node-ip>:30300
    protocol: TCP
