apiVersion: v1
kind: Service
metadata:
  name: freshness-classifier
  namespace: freshness
  labels:
    app: freshness-classifier
spec:
  type: NodePort
  selector:
    app: freshness-classifier
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30800  
    protocol: TCP